server:
  port: 8080

spring:
  application:
    name: acl-api

legacy:
  base-url: https://legacy.example.com

resilience4j:
  circuitbreaker:
    instances:
      legacy:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
  retry:
    instances:
      legacy:
        max-attempts: 3
        wait-duration: 200ms
  timelimiter:
    instances:
      legacy:
        timeout-duration: 3s
